osx_image: xcode10.1
language: objective-c
cache:
  directories:
  - Carthage
env:
  global:
  - FRAMEWORK_NAME=HugeTabBarButton
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
script:
- set -o pipefail && xcodebuild test -scheme $FRAMEWORK_NAME -destination 'platform=iOS
  Simulator,name=iPhone XS,OS=12.1' ONLY_ACTIVE_ARCH=YES | xcpretty
deploy:
  provider: releases
  api_key:
    secure: XHi0WhS1jQ14Y+aYIE/zzI718PKDHniDQ73n6NYYQXo0TUVYqto54nZ3jzwHC4ncNBJAo22SlgluqVmcd4IiAhZDZsJ1JnuTT5SrVGN82YTyqR0q1ilhB7xYNS/IC7NRUSmFNNtFHl1zW6qWdpKQVovcUDHTZH9BG18odqUP8Zf63/CVyxBOitTpI3ow0KDUHgYSGSZsuqUDHSj070m7Q3wW7DxB/saxTVrbIgSsW0DIEEIZyIj57k+Wv72d83knRcig4B3djwqNWghb/0gKQj1ATFNEEtnS/zpalYDiAYpab6gVsYf7rBaE482EABq7vAeoZEE8uKhXC2OOqPiBIIZcAlmcaG36SbVyg60ESJ0bpOWclOPG9+fMYLJi+YX72IuhHL0KwpIcg4/iihBytff8Pk5yRMMsDiX2Gwp7U3vc3ITbuP0BJnNRYlJbVvLoKhydsETWftvskk3zBulPxCCK6AP3BA0Zqp+127hcJPEh58H7Hl7plWwey6P/5YJurF4XFXLOk21A36voL6EXpaMAhwL0pOnzDj+TO5SNVyGPHYpHL0NI+GGEFZo8c0c0AgKIgaIo6O2F7Ak1rndLjFWp44eL4wkYsMt+7cA5IMKXGgSnngYd2vWhxLCFb3MurfkPK1nM58S5YI2jUdn9O1XyM03ittgarKelIBEdwug=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: fortmarek/HugeTabBarButton
    tags: true
